# Generated by Django 5.0.6 on 2024-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_service_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dj_service_description', models.CharField(blank=True, max_length=250, null=True)),
                ('dj_fully_booked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'DJ Service',
                'verbose_name_plural': 'DJ Services',
            },
        ),
    ]
