# Generated by Django 5.0.6 on 2024-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_review', models.DateField(auto_now_add=True)),
                ('review_event_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_event', models.DateField(blank=True, null=True)),
                ('event_city', models.CharField(blank=True, max_length=250, null=True)),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')])),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
