# Generated by Django 5.0.6 on 2024-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_pass',
            field=models.BooleanField(default=False),
        ),
    ]
