# Generated by Django 5.0.14 on 2025-06-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_reviews_rating_message_dj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCloudEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_html', models.TextField(default='<p>Nothing to Show</p>')),
                ('show_date', models.DateField()),
            ],
        ),
    ]
