# Generated by Django 4.2.3 on 2023-07-30 18:11

from django.db import migrations, models
import frontend.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_contact_info',
            fields=[
                ('customer_id', models.CharField(default=frontend.models.customer_id_gen, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_email', models.EmailField(max_length=255)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, region=None)),
                ('customer_contact_subject', models.CharField(blank=True, choices=[('Website Issue', 'Website Issue'), ('Website Consult', 'Website Consult'), ('Ecommerce Consult', 'Ecommerce Consult'), ('Website Design', 'Website Design'), ('Website Updates', 'Website Updates'), ('Integrations', 'Integrations'), ('Other', 'Other')], max_length=30, null=True)),
                ('customer_notes', models.TextField(help_text='Why ya wanna reach out here?')),
                ('internal_progress', models.CharField(blank=True, choices=[('RECEIVED', 'RECEIVED'), ('AKNOWLEDGED', 'AKNOWLEDGED'), ('CONTACTED', 'CONTACTED'), ('IN PROGRESS', 'IN PROGRESS'), ('IN REVIEW', 'IN REVIEW'), ('DONE', 'DONE')], max_length=20, null=True)),
                ('work_estimate', models.FloatField(blank=True, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
