# Generated by Django 4.2.3 on 2023-07-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_contact_info',
            name='internal_customer_contact_subject',
            field=models.CharField(blank=True, choices=[('Website Issue', 'Website Issue'), ('Website Consult', 'Website Consult'), ('Ecommerce Consult', 'Ecommerce Consult'), ('Website Design', 'Website Design'), ('Website Updates', 'Website Updates'), ('Integrations', 'Integrations'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer_contact_info',
            name='customer_contact_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
