# Generated by Django 4.2.3 on 2023-08-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_customer_contact_info_internal_customer_contact_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_contact_info',
            name='submission_time',
            field=models.DateField(auto_now=True),
        ),
    ]
