# Generated by Django 5.0.2 on 2024-04-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_customer_contact_info_submission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('emp_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_specialties_1', models.CharField(blank=True, max_length=250, null=True)),
                ('emp_specialties_2', models.CharField(blank=True, max_length=250, null=True)),
                ('emp_specialties_3', models.CharField(blank=True, max_length=250, null=True)),
                ('emp_bio', models.TextField(blank=True, null=True)),
                ('active_employee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
