# Generated by Django 5.0.6 on 2024-05-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_djservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjServices',
        ),
    ]
